CREATE TABLE chats (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '对话唯一标识',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '对话创建时间',
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '对话最后活跃时间',
    PRIMARY KEY (id)
) ENGINE=InnoDB COMMENT='用户与 Gateway Agent 的持续对话';
