// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: approval.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const decideApproval = `-- name: DecideApproval :execrows
UPDATE approvals
SET status = ?,
    updated_at = CURRENT_TIMESTAMP(6)
WHERE id = ?
  AND chat_id = ?
  AND status = 'pending'
`

type DecideApprovalParams struct {
	Status string `json:"status"`
	ID     uint64 `json:"id"`
	ChatID uint64 `json:"chat_id"`
}

func (q *Queries) DecideApproval(ctx context.Context, arg DecideApprovalParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, decideApproval, arg.Status, arg.ID, arg.ChatID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getApproval = `-- name: GetApproval :one
SELECT id,
       chat_id,
       status,
       operation,
       arguments,
       resume_target,
       runtime_state,
       created_at,
       updated_at
FROM approvals
WHERE id = ?
  AND chat_id = ?
`

type GetApprovalParams struct {
	ID     uint64 `json:"id"`
	ChatID uint64 `json:"chat_id"`
}

func (q *Queries) GetApproval(ctx context.Context, arg GetApprovalParams) (Approval, error) {
	row := q.db.QueryRowContext(ctx, getApproval, arg.ID, arg.ChatID)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.Status,
		&i.Operation,
		&i.Arguments,
		&i.ResumeTarget,
		&i.RuntimeState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertApproval = `-- name: InsertApproval :execresult
INSERT INTO approvals (chat_id, status, operation, arguments, resume_target, runtime_state)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertApprovalParams struct {
	ChatID       uint64          `json:"chat_id"`
	Status       string          `json:"status"`
	Operation    string          `json:"operation"`
	Arguments    json.RawMessage `json:"arguments"`
	ResumeTarget string          `json:"resume_target"`
	RuntimeState []byte          `json:"runtime_state"`
}

func (q *Queries) InsertApproval(ctx context.Context, arg InsertApprovalParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertApproval,
		arg.ChatID,
		arg.Status,
		arg.Operation,
		arg.Arguments,
		arg.ResumeTarget,
		arg.RuntimeState,
	)
}

const listPendingApprovals = `-- name: ListPendingApprovals :many
SELECT id,
       chat_id,
       status,
       operation,
       arguments,
       created_at,
       updated_at
FROM approvals
WHERE chat_id = ?
  AND status = 'pending'
ORDER BY id
`

type ListPendingApprovalsRow struct {
	ID        uint64          `json:"id"`
	ChatID    uint64          `json:"chat_id"`
	Status    string          `json:"status"`
	Operation string          `json:"operation"`
	Arguments json.RawMessage `json:"arguments"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

func (q *Queries) ListPendingApprovals(ctx context.Context, chatID uint64) ([]ListPendingApprovalsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingApprovals, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingApprovalsRow{}
	for rows.Next() {
		var i ListPendingApprovalsRow
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.Status,
			&i.Operation,
			&i.Arguments,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
