// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: chat.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getChat = `-- name: GetChat :one
SELECT id, model_config_id, created_at, updated_at
FROM chats
WHERE id = ?
`

func (q *Queries) GetChat(ctx context.Context, id uint64) (Chat, error) {
	row := q.db.QueryRowContext(ctx, getChat, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.ModelConfigID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChatForUpdate = `-- name: GetChatForUpdate :one
SELECT id
FROM chats
WHERE id = ?
FOR UPDATE
`

func (q *Queries) GetChatForUpdate(ctx context.Context, id uint64) (uint64, error) {
	row := q.db.QueryRowContext(ctx, getChatForUpdate, id)
	err := row.Scan(&id)
	return id, err
}

const insertChat = `-- name: InsertChat :execresult
INSERT INTO chats (model_config_id)
VALUES (?)
`

func (q *Queries) InsertChat(ctx context.Context, modelConfigID *uint64) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertChat, modelConfigID)
}

const touchChat = `-- name: TouchChat :execrows
UPDATE chats
SET updated_at = GREATEST(CURRENT_TIMESTAMP(6), TIMESTAMPADD(MICROSECOND, 1, updated_at))
WHERE id = ?
`

func (q *Queries) TouchChat(ctx context.Context, id uint64) (int64, error) {
	result, err := q.db.ExecContext(ctx, touchChat, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
