// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: chat_message.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getChatMessage = `-- name: GetChatMessage :one
SELECT id, chat_id, role, content, created_at
FROM chat_messages
WHERE id = ?
`

func (q *Queries) GetChatMessage(ctx context.Context, id uint64) (ChatMessage, error) {
	row := q.db.QueryRowContext(ctx, getChatMessage, id)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const insertChatMessage = `-- name: InsertChatMessage :execresult
INSERT INTO chat_messages (chat_id, role, content)
VALUES (?, ?, ?)
`

type InsertChatMessageParams struct {
	ChatID  uint64 `json:"chat_id"`
	Role    string `json:"role"`
	Content string `json:"content"`
}

func (q *Queries) InsertChatMessage(ctx context.Context, arg InsertChatMessageParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertChatMessage, arg.ChatID, arg.Role, arg.Content)
}

const listChatMessagesAfter = `-- name: ListChatMessagesAfter :many
SELECT id, chat_id, role, content, created_at
FROM chat_messages
WHERE chat_id = ?
  AND id > ?
ORDER BY id
LIMIT ?
`

type ListChatMessagesAfterParams struct {
	ChatID uint64 `json:"chat_id"`
	ID     uint64 `json:"id"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) ListChatMessagesAfter(ctx context.Context, arg ListChatMessagesAfterParams) ([]ChatMessage, error) {
	rows, err := q.db.QueryContext(ctx, listChatMessagesAfter, arg.ChatID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMessage{}
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentChatMessages = `-- name: ListRecentChatMessages :many
SELECT id, chat_id, role, content, created_at
FROM chat_messages
WHERE chat_id = ?
ORDER BY id DESC
LIMIT ?
`

type ListRecentChatMessagesParams struct {
	ChatID uint64 `json:"chat_id"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) ListRecentChatMessages(ctx context.Context, arg ListRecentChatMessagesParams) ([]ChatMessage, error) {
	rows, err := q.db.QueryContext(ctx, listRecentChatMessages, arg.ChatID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMessage{}
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
