// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package apiserver

import (
	"github.com/lgc202/gateway-agent/internal/apiserver/config"
	chat2 "github.com/lgc202/gateway-agent/internal/apiserver/handler/chat"
	"github.com/lgc202/gateway-agent/internal/apiserver/handler/health"
	modelconfig2 "github.com/lgc202/gateway-agent/internal/apiserver/handler/modelconfig"
	"github.com/lgc202/gateway-agent/internal/apiserver/server"
	"github.com/lgc202/gateway-agent/internal/apiserver/service/agent"
	"github.com/lgc202/gateway-agent/internal/apiserver/service/chat"
	"github.com/lgc202/gateway-agent/internal/apiserver/service/modelconfig"
	"github.com/lgc202/gateway-agent/internal/apiserver/store/mysql"
)

// Injectors from wire.go:

// InitializeServer 装配 apiserver 当前运行所需的全部依赖
func InitializeServer(configFile string) (*server.Server, error) {
	configConfig, err := config.Load(configFile)
	if err != nil {
		return nil, err
	}
	db, err := mysql.NewDB(configConfig)
	if err != nil {
		return nil, err
	}
	store := mysql.NewStore(db)
	service, err := modelconfig.New(configConfig, store)
	if err != nil {
		return nil, err
	}
	factory := agent.NewFactory(configConfig, service)
	chatService := chat.New(store, factory)
	handler := chat2.New(chatService)
	modelconfigHandler := modelconfig2.New(service)
	healthHandler := health.New(db)
	serverServer := server.New(configConfig, db, handler, modelconfigHandler, healthHandler)
	return serverServer, nil
}
