// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: model_config.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countChatsByModelConfigID = `-- name: CountChatsByModelConfigID :one
SELECT COUNT(*)
FROM chats
WHERE model_config_id = ?
`

func (q *Queries) CountChatsByModelConfigID(ctx context.Context, modelConfigID *uint64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChatsByModelConfigID, modelConfigID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteModelConfig = `-- name: DeleteModelConfig :execrows
DELETE
FROM model_configs
WHERE id = ?
`

func (q *Queries) DeleteModelConfig(ctx context.Context, id uint64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteModelConfig, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getModelConfig = `-- name: GetModelConfig :one
SELECT id,
       name,
       provider,
       model,
       base_url,
       max_tokens,
       api_key IS NOT NULL AS api_key_configured,
       created_at,
       updated_at
FROM model_configs
WHERE id = ?
`

type GetModelConfigRow struct {
	ID               uint64    `json:"id"`
	Name             string    `json:"name"`
	Provider         string    `json:"provider"`
	Model            string    `json:"model"`
	BaseURL          string    `json:"base_url"`
	MaxTokens        uint32    `json:"max_tokens"`
	APIKeyConfigured bool      `json:"api_key_configured"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

func (q *Queries) GetModelConfig(ctx context.Context, id uint64) (GetModelConfigRow, error) {
	row := q.db.QueryRowContext(ctx, getModelConfig, id)
	var i GetModelConfigRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.Model,
		&i.BaseURL,
		&i.MaxTokens,
		&i.APIKeyConfigured,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModelConfigAPIKey = `-- name: GetModelConfigAPIKey :one
SELECT api_key
FROM model_configs
WHERE id = ?
`

func (q *Queries) GetModelConfigAPIKey(ctx context.Context, id uint64) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getModelConfigAPIKey, id)
	var api_key []byte
	err := row.Scan(&api_key)
	return api_key, err
}

const insertModelConfig = `-- name: InsertModelConfig :execresult
INSERT INTO model_configs (name, provider, model, base_url, api_key, max_tokens)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertModelConfigParams struct {
	Name      string `json:"name"`
	Provider  string `json:"provider"`
	Model     string `json:"model"`
	BaseURL   string `json:"base_url"`
	APIKey    []byte `json:"api_key"`
	MaxTokens uint32 `json:"max_tokens"`
}

func (q *Queries) InsertModelConfig(ctx context.Context, arg InsertModelConfigParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertModelConfig,
		arg.Name,
		arg.Provider,
		arg.Model,
		arg.BaseURL,
		arg.APIKey,
		arg.MaxTokens,
	)
}

const listModelConfigs = `-- name: ListModelConfigs :many
SELECT id,
       name,
       provider,
       model,
       base_url,
       max_tokens,
       api_key IS NOT NULL AS api_key_configured,
       created_at,
       updated_at
FROM model_configs
ORDER BY id
`

type ListModelConfigsRow struct {
	ID               uint64    `json:"id"`
	Name             string    `json:"name"`
	Provider         string    `json:"provider"`
	Model            string    `json:"model"`
	BaseURL          string    `json:"base_url"`
	MaxTokens        uint32    `json:"max_tokens"`
	APIKeyConfigured bool      `json:"api_key_configured"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

func (q *Queries) ListModelConfigs(ctx context.Context) ([]ListModelConfigsRow, error) {
	rows, err := q.db.QueryContext(ctx, listModelConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListModelConfigsRow{}
	for rows.Next() {
		var i ListModelConfigsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Provider,
			&i.Model,
			&i.BaseURL,
			&i.MaxTokens,
			&i.APIKeyConfigured,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateModelConfig = `-- name: UpdateModelConfig :execrows
UPDATE model_configs
SET name = ?,
    provider = ?,
    model = ?,
    base_url = ?,
    max_tokens = ?,
    updated_at = CURRENT_TIMESTAMP(6)
WHERE id = ?
`

type UpdateModelConfigParams struct {
	Name      string `json:"name"`
	Provider  string `json:"provider"`
	Model     string `json:"model"`
	BaseURL   string `json:"base_url"`
	MaxTokens uint32 `json:"max_tokens"`
	ID        uint64 `json:"id"`
}

func (q *Queries) UpdateModelConfig(ctx context.Context, arg UpdateModelConfigParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateModelConfig,
		arg.Name,
		arg.Provider,
		arg.Model,
		arg.BaseURL,
		arg.MaxTokens,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateModelConfigAPIKey = `-- name: UpdateModelConfigAPIKey :execrows
UPDATE model_configs
SET api_key = ?,
    updated_at = CURRENT_TIMESTAMP(6)
WHERE id = ?
`

type UpdateModelConfigAPIKeyParams struct {
	APIKey []byte `json:"api_key"`
	ID     uint64 `json:"id"`
}

func (q *Queries) UpdateModelConfigAPIKey(ctx context.Context, arg UpdateModelConfigAPIKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateModelConfigAPIKey, arg.APIKey, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
